version: '3.8'

services:
  web:
    build: .
#    command: python /code/manage.py runserver_plus --cert-file cert.crt 0.0.0.0:8000
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
#    environment:
#      - "DJANGO_SECURE_SSL_REDIRECT=False"
#      - "DJANGO_SECURE_HSTS_SECONDS=0"
#      - "DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS=False"
#      - "DJANGO_SECURE_HSTS_PRELOAD=False"
#      - "DJANGO_SESSION_COOKIE_SECURE=False"
#      - "DJANGO_CSRF_COOKIE_SECURE=False"
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
  postgres_data: