# Generated by Django 3.2.9 on 2021-11-09 00:20

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('tramitacoes', '0002_historicaltramite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltramite',
            name='despacho',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tramite',
            name='despacho',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
