# Generated by Django 3.2.9 on 2021-12-29 00:38

import apps.tramitacoes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramitacoes', '0003_auto_20211108_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltramite',
            name='anexo',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tramite',
            name='anexo',
            field=models.FileField(blank=True, null=True, upload_to=apps.tramitacoes.models.anexo_tramite_path),
        ),
    ]
