# Generated by Django 3.2.7 on 2021-09-19 19:33

import cnpj_field.models
import cpf_field.models
from django.db import migrations, models
import django_cryptography.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interessado',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(help_text='Nome ou Razão Social', max_length=100)),
                ('nome_social', models.CharField(blank=True, max_length=100, null=True)),
                ('cpf', django_cryptography.fields.encrypt(cpf_field.models.CPFField(blank=True, max_length=14, null=True, unique=True, verbose_name='cpf'))),
                ('cnpj', cnpj_field.models.CNPJField(blank=True, max_length=14, null=True, unique=True, verbose_name='cnpj')),
            ],
        ),
    ]
