# Generated by Django 3.2.7 on 2021-11-01 20:40

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interessados', '0003_interessado_data_nascimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interessado',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True, validators=[apps.core.validators.validate_data_nascimento]),
        ),
    ]
