# Generated by Django 3.2.5 on 2021-08-04 01:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assuntos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('num_processo', models.PositiveBigIntegerField(auto_created=True, editable=False, unique_for_year=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('interessado', models.CharField(max_length=200)),
                ('resumo', models.TextField(blank=True, null=True)),
                ('situacao', models.CharField(choices=[('A', 'Ativo'), ('E', 'Encerrado')], default='A', max_length=2)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('assunto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='processos_assunto', to='assuntos.assunto')),
                ('usuario_alteracao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='processos_alterados', to=settings.AUTH_USER_MODEL)),
                ('usuario_criacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='processos_usuario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
