# Generated by Django 3.2.5 on 2021-08-04 02:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('processos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processo',
            name='num_processo',
            field=models.PositiveBigIntegerField(editable=False, unique_for_year=True),
        ),
        migrations.AlterField(
            model_name='processo',
            name='usuario_alteracao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='processos_alterados', to=settings.AUTH_USER_MODEL),
        ),
    ]
