# Generated by Django 3.2.5 on 2021-08-05 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0002_auto_20210803_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processo',
            name='num_processo',
            field=models.PositiveBigIntegerField(default=0, editable=False, unique_for_year=True),
        ),
    ]
