# Generated by Django 3.2.5 on 2021-08-05 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0003_alter_processo_num_processo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processo',
            name='num_processo',
            field=models.PositiveBigIntegerField(default=0, editable=False, unique_for_year='2021'),
        ),
    ]
