# Generated by Django 3.2.5 on 2021-08-12 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0004_alter_processo_num_processo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='processo',
            options={'ordering': ['-data_criacao']},
        ),
    ]
