# Generated by Django 3.2.5 on 2021-08-20 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0005_alter_processo_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='processo',
            name='unidade_atual',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
