# Generated by Django 3.2.6 on 2021-08-28 02:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assuntos', '0001_initial'),
        ('processos', '0006_processo_unidade_atual'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalProcesso',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('num_processo', models.PositiveBigIntegerField(default=0, editable=False, unique_for_year='2021')),
                ('interessado', models.CharField(max_length=200)),
                ('resumo', models.TextField(blank=True, null=True)),
                ('situacao', models.CharField(choices=[('A', 'Ativo'), ('E', 'Encerrado')], default='A', max_length=2)),
                ('data_criacao', models.DateTimeField(blank=True, editable=False)),
                ('data_atualizacao', models.DateTimeField(blank=True, editable=False)),
                ('unidade_atual', models.CharField(blank=True, max_length=100, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('assunto', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='assuntos.assunto')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario_alteracao', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario_criacao', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical processo',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
