# Generated by Django 3.2.7 on 2021-09-27 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interessados', '0002_alter_interessado_cpf'),
        ('processos', '0008_auto_20210926_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprocesso',
            name='interessado',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='interessados.interessado'),
        ),
        migrations.AddField(
            model_name='processo',
            name='interessado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='processos_interessado', to='interessados.interessado'),
        ),
    ]
