# Generated by Django 3.2.9 on 2021-12-18 21:26

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0009_auto_20210926_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalprocesso',
            name='resumo',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='processo',
            name='resumo',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
