# Generated by Django 3.2.9 on 2021-12-26 23:52

import apps.processos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0010_auto_20211218_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprocesso',
            name='anexo',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='processo',
            name='anexo',
            field=models.FileField(blank=True, null=True, upload_to=apps.processos.models.interessado_processo_path),
        ),
    ]
