# Generated by Django 4.0 on 2022-01-04 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0011_auto_20211226_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalprocesso',
            name='num_processo',
            field=models.PositiveBigIntegerField(default=0, editable=False, unique_for_year='2022'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='num_processo',
            field=models.PositiveBigIntegerField(default=0, editable=False, unique_for_year='2022'),
        ),
    ]
