# Generated by Django 4.0.2 on 2023-04-06 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0012_alter_historicalprocesso_num_processo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalprocesso',
            name='num_processo',
            field=models.PositiveBigIntegerField(default=0, editable=False, unique_for_year='2023'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='num_processo',
            field=models.PositiveBigIntegerField(default=0, editable=False, unique_for_year='2023'),
        ),
    ]
