# Generated by Django 3.2.5 on 2021-07-18 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210711_1731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='matricula',
        ),
    ]
