# Generated by Django 3.2.5 on 2021-07-18 02:57

import cpf_field.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_customuser_matricula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='cpf',
            field=cpf_field.models.CPFField(blank=True, max_length=14, null=True, unique=True, verbose_name='cpf'),
        ),
    ]
