# Generated by Django 3.2.5 on 2021-07-15 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cargos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cargos',
            new_name='Cargo',
        ),
    ]
