# Generated by Django 3.2.5 on 2021-07-15 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargos', '0002_rename_cargos_cargo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='jornada',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
