# Generated by Django 3.2.5 on 2021-07-25 20:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orgaos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cargos', '0004_vinculo'),
    ]

    operations = [
        migrations.AddField(
            model_name='vinculo',
            name='lotacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vinculos_lotados', to='orgaos.orgao'),
        ),
        migrations.AlterField(
            model_name='vinculo',
            name='funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vinculos', to=settings.AUTH_USER_MODEL),
        ),
    ]
