# Generated by Django 3.2.9 on 2021-12-24 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cargos', '0005_auto_20210725_1749'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cargo',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='vinculo',
            options={'ordering': ['-data_inclusao']},
        ),
    ]
