# Generated by Django 3.2.5 on 2021-07-21 02:50

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orgao',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('sigla', models.CharField(blank=True, max_length=10, null=True)),
                ('tipo', models.CharField(choices=[('F', 'Formal'), ('I', 'Informal')], default='F', max_length=2)),
                ('situacao', models.CharField(choices=[('A', 'Ativa'), ('I', 'Inativa')], default='A', max_length=2)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('superior', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='orgaos.orgao')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
