# Generated by Django 3.2.5 on 2021-07-21 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgaos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orgao',
            old_name='superior',
            new_name='parent',
        ),
    ]
