# Generated by Django 3.2.5 on 2021-07-21 03:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orgaos', '0002_rename_superior_orgao_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgao',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
